### ISSUE TITLE
Error: Failed to launch the browser process

### ISSUE THREAD

**Issue by tio-plato** [MelosBot/Workflows-Sample#8]
配置完成后运行出现报错

Github Action 中的提示是
```
npm WARN deprecated request@2.88.2: request has been deprecated, see request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

> puppeteer@2.1.1 install /home/runner/work/Workflows-Sample/Workflows-Sample/workdir/node_modules/puppeteer
> node install.js


Chromium downloaded to /home/runner/work/Workflows-Sample/Workflows-Sample/workdir/node_modules/puppeteer/.local-chromium/linux-722234
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN xmpp-jid@1.3.0 requires a peer of node-stringprep@^0.8.0 but none is installed. You must install peer dependencies yourself.

added 309 packages from 248 contributors and audited 309 packages in 12.927s

12 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Error: Process completed with exit code 1.
```
TGbot推送的信息是
```
ERROR | Error: Failed to launch the browser process!
2109:2109:1216/044213.038025:ERROR:browser\_main\_loop.cc(1512) Unable to open X display.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/runner/work/Workflows-Sample/Workflows-Sample/workdir/node_modules/puppeteer/lib/Launcher.js:750:14)
    at ChildProcess.<anonymous> (/home/runner/work/Workflows-Sample/Workflows-Sample/workdir/node_modules/puppeteer/lib/Launcher.js:740:61)
    at ChildProcess.emit (events.js:327:22)
```

**Comment by BitaminKim** [comment]
一样
